### ISSUE TITLE
Clock crashed

### ISSUE THREAD

**Issue by phxql** [phxql/restwars#67]
```
ERROR [2015-02-15 16:57:59,650] restwars.rest.Clock: Clock thread crashed with exception
! org.h2.jdbc.JdbcSQLException: Eindeutiger Index oder Primärschlüssel verletzt: "CONSTRAINT_INDEX_B ON PUBLIC.TECHNOLOGY(PLAYER_ID, TYPE) VALUES ( /* key:2 */ null, 1, null, '2d821735-a30f-49b1-b7b1-519a00630131')"
! Unique index or primary key violation: "CONSTRAINT_INDEX_B ON PUBLIC.TECHNOLOGY(PLAYER_ID, TYPE) VALUES ( /* key:2 */ null, 1, null, '2d821735-a30f-49b1-b7b1-519a00630131')"; SQL statement:
! insert into "PUBLIC"."TECHNOLOGY" ("ID", "TYPE", "PLAYER_ID", "LEVEL") values (cast(? as uuid), cast(? as int), cast(? as uuid), cast(? as int)) [23505-176]
! at org.h2.message.DbException.getJdbcSQLException(DbException.java:344) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.message.DbException.get(DbException.java:178) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.message.DbException.get(DbException.java:154) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:103) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.index.PageBtree.find(PageBtree.java:121) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.index.PageBtreeLeaf.addRow(PageBtreeLeaf.java:151) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.index.PageBtreeLeaf.addRowTry(PageBtreeLeaf.java:104) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.index.PageBtreeIndex.addRow(PageBtreeIndex.java:97) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.index.PageBtreeIndex.add(PageBtreeIndex.java:88) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.table.RegularTable.addRow(RegularTable.java:120) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.command.dml.Insert.insertRows(Insert.java:157) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.command.dml.Insert.update(Insert.java:115) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.command.CommandContainer.update(CommandContainer.java:79) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.command.Command.executeUpdate(Command.java:254) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:199) ~[h2-1.3.176.jar:1.3.176]
! at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:194) ~[jooq-3.4.1.jar:na]
! at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:395) ~[jooq-3.4.1.jar:na]
! at org.jooq.impl.AbstractStoreQuery.execute(AbstractStoreQuery.java:276) ~[jooq-3.4.1.jar:na]
! at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:331) ~[jooq-3.4.1.jar:na]
! ... 11 common frames omitted
! Causing: org.jooq.exception.DataAccessException: SQL [insert into "PUBLIC"."TECHNOLOGY" ("ID", "TYPE", "PLAYER_ID", "LEVEL") values (cast(? as uuid), cast(? as int), cast(? as uuid), cast(? as int))]; Eindeutiger Index oder Primärschlüssel verletzt: "CONSTRAINT_INDEX_B ON PUBLIC.TECHNOLOGY(PLAYER_ID, TYPE) VALUES ( /* key:2 */ null, 1, null, '2d821735-a30f-49b1-b7b1-519a00630131')"
! Unique index or primary key violation: "CONSTRAINT_INDEX_B ON PUBLIC.TECHNOLOGY(PLAYER_ID, TYPE) VALUES ( /* key:2 */ null, 1, null, '2d821735-a30f-49b1-b7b1-519a00630131')"; SQL statement:
! insert into "PUBLIC"."TECHNOLOGY" ("ID", "TYPE", "PLAYER_ID", "LEVEL") values (cast(? as uuid), cast(? as int), cast(? as uuid), cast(? as int)) [23505-176]
! at org.jooq.impl.Utils.translate(Utils.java:1428) ~[jooq-3.4.1.jar:na]
! at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:505) ~[jooq-3.4.1.jar:na]
! at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:340) ~[jooq-3.4.1.jar:na]
! at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:133) ~[jooq-3.4.1.jar:na]
! at restwars.storage.technology.JooqTechnologyDAO.insert(JooqTechnologyDAO.java:84) ~[storage-1.0-SNAPSHOT.jar:na]
! at restwars.service.technology.impl.TechnologyServiceImpl.finishResearches(TechnologyServiceImpl.java:85) ~[service-1.0-SNAPSHOT.jar:na]
! at restwars.rest.Clock.run(Clock.java:78) ~[rest-1.0-SNAPSHOT.jar:na]
! at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_31]
! at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [na:1.8.0_31]
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [na:1.8.0_31]
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_31]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_31]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_31]
! at java.lang.Thread.run(Unknown Source) [na:1.8.0_31]
```

**Comment by phxql** [comment]
This happens when research for combustion engine level 2 is finished.
