### ISSUE TITLE
Database deadlock

### ISSUE THREAD

**Issue by phxql** [phxql/restwars#68]
```
ERROR [2015-02-15 17:39:13,342] restwars.rest.Clock: Clock thread crashed with exception
! org.h2.jdbc.JdbcSQLException: Eine Verklemmung (Deadlock) ist aufgetreten. Die aktuelle Transaktion wurde rückgängig gemacht. Details: "
! Session #11 (user: ) on thread dw-89 - POST /v1/planet/8.4.2/ship-in-construction is waiting to lock PUBLIC.ROUND while locking PUBLIC.PLANET (exclusive).
! Session #12 (user: ) on thread pool-2-thread-1 is waiting to lock PUBLIC.PLANET while locking PUBLIC.ROUND (exclusive), PUBLIC.BUILDING (exclusive), PUBLIC.EVENT (exclusive)."
! Deadlock detected. The current transaction was rolled back. Details: "
! Session #11 (user: ) on thread dw-89 - POST /v1/planet/8.4.2/ship-in-construction is waiting to lock PUBLIC.ROUND while locking PUBLIC.PLANET (exclusive).
! Session #12 (user: ) on thread pool-2-thread-1 is waiting to lock PUBLIC.PLANET while locking PUBLIC.ROUND (exclusive), PUBLIC.BUILDING (exclusive), PUBLIC.EVENT (exclusive)."; SQL statement:
! insert into "PUBLIC"."EVENT" ("ID", "PLAYER_ID", "PLANET_ID", "TYPE", "ROUND", "FIGHT_ID") values (cast(? as uuid), cast(? as uuid), cast(? as uuid), cast(? as int), cast(? as bigint), cast(? as uuid)) [40001-176]
! at org.h2.message.DbException.getJdbcSQLException(DbException.java:344) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.message.DbException.get(DbException.java:178) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.message.DbException.get(DbException.java:154) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.table.RegularTable.doLock(RegularTable.java:518) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.table.RegularTable.lock(RegularTable.java:464) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.constraint.ConstraintReferential.existsRow(ConstraintReferential.java:381) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.constraint.ConstraintReferential.checkRowOwnTable(ConstraintReferential.java:372) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:315) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.table.Table.fireConstraints(Table.java:909) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.table.Table.fireAfterRow(Table.java:927) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.command.dml.Insert.insertRows(Insert.java:162) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.command.dml.Insert.update(Insert.java:115) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.command.CommandContainer.update(CommandContainer.java:79) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.command.Command.executeUpdate(Command.java:254) ~[h2-1.3.176.jar:1.3.176]
! at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:199) ~[h2-1.3.176.jar:1.3.176]
! at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:194) ~[jooq-3.4.1.jar:na]
! at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:395) ~[jooq-3.4.1.jar:na]
! at org.jooq.impl.AbstractStoreQuery.execute(AbstractStoreQuery.java:276) ~[jooq-3.4.1.jar:na]
! at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:331) ~[jooq-3.4.1.jar:na]
! ... 13 common frames omitted
! Causing: org.jooq.exception.DataAccessException: SQL [insert into "PUBLIC"."EVENT" ("ID", "PLAYER_ID", "PLANET_ID", "TYPE", "ROUND", "FIGHT_ID") values (cast(? as uuid), cast(? as uuid), cast(? as uuid), cast(? as int), cast(? as bigint), cast(? as uuid))]; Eine Verklemmung (Deadlock) ist aufgetreten. Die aktuelle Transaktion wurde rückgängig gemacht. Details: "
! Session #11 (user: ) on thread dw-89 - POST /v1/planet/8.4.2/ship-in-construction is waiting to lock PUBLIC.ROUND while locking PUBLIC.PLANET (exclusive).
! Session #12 (user: ) on thread pool-2-thread-1 is waiting to lock PUBLIC.PLANET while locking PUBLIC.ROUND (exclusive), PUBLIC.BUILDING (exclusive), PUBLIC.EVENT (exclusive)."
! Deadlock detected. The current transaction was rolled back. Details: "
! Session #11 (user: ) on thread dw-89 - POST /v1/planet/8.4.2/ship-in-construction is waiting to lock PUBLIC.ROUND while locking PUBLIC.PLANET (exclusive).
! Session #12 (user: ) on thread pool-2-thread-1 is waiting to lock PUBLIC.PLANET while locking PUBLIC.ROUND (exclusive), PUBLIC.BUILDING (exclusive), PUBLIC.EVENT (exclusive)."; SQL statement:
! insert into "PUBLIC"."EVENT" ("ID", "PLAYER_ID", "PLANET_ID", "TYPE", "ROUND", "FIGHT_ID") values (cast(? as uuid), cast(? as uuid), cast(? as uuid), cast(? as int), cast(? as bigint), cast(? as uuid)) [40001-176]
! at org.jooq.impl.Utils.translate(Utils.java:1428) ~[jooq-3.4.1.jar:na]
! at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:505) ~[jooq-3.4.1.jar:na]
! at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:340) ~[jooq-3.4.1.jar:na]
! at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:133) ~[jooq-3.4.1.jar:na]
! at restwars.storage.event.JooqEventDAO.insert(JooqEventDAO.java:41) ~[classes/:na]
! at restwars.service.event.impl.EventServiceImpl.createSimpleEvent(EventServiceImpl.java:141) ~[classes/:na]
! at restwars.service.event.impl.EventServiceImpl.createBuildingCompletedEvent(EventServiceImpl.java:46) ~[classes/:na]
! at restwars.service.building.impl.BuildingServiceImpl.finishConstructionSites(BuildingServiceImpl.java:190) ~[classes/:na]
! at restwars.rest.Clock.run(Clock.java:77) ~[classes/:na]
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_25]
! at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_25]
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_25]
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_25]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
```

**Comment by phxql** [comment]
Maybe thats related to a fixed H2 bug? See item in (http://www.h2database.com/html/changelog.html)[H2 Changelog] for Version 1.4.183 Beta (2014-12-13).

**Comment by phxql** [comment]
This bug shouldn't occur any more. The concurrency between client requests and the clock has been improved.
